export interface TrendingColor {
  name: string;
  class: string;
}

export interface TrendingProduct {
  name: string;
  price: string;
  image?: string;
  imageUrl?: string;
  variant?: string;
  priceValue?: number;
  badge?: string;
  moreColors?: string;
  swatches?: string[];
  sizes?: string[];
  colors?: string[];
  productType?: string;
  material?: string;
  categories: string[];
}

export const TRENDING_FILTERS = [
  "Men's Fashion",
  "Women's Fashion",
  "Men's Accessories",
  "Women's Accessories",
  'Discount Deals',
] as const;

export const TRENDING_COLORS: TrendingColor[] = [
  { name: 'PINK', class: 'bg-[#F44E8A]' },
  { name: 'DARK GREEN', class: 'bg-[#44936D]' },
  { name: 'YELLOW', class: 'bg-[#F4CF4E]' },
  { name: 'BLUE SKY', class: 'bg-[#5FABE2]' },
  { name: 'NAVY BLUE', class: 'bg-[#233C6B]' },
  { name: 'CLEAN WHITE', class: 'bg-[#FFFFFF] border border-[#DEDEDE]' },
  { name: 'RED PASTEL', class: 'bg-[#E25F5F]' },
];

export const FALLBACK_TRENDING_PRODUCTS: TrendingProduct[] = [
  {
    name: "Men's Dasher Knit",
    variant: 'Graphite',
    price: '$140',
    priceValue: 140,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'NEW',
    moreColors: '+6',
    swatches: ['#3A3D43', '#6D727A', '#B4BAC2'],
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['Black', 'Grey'],
    productType: 'Running Shoes',
    material: 'Tree',
    categories: ["Men's Fashion", 'Discount Deals'],
  },
  {
    name: "Men's Canvas Cruiser",
    variant: 'Steel Blue',
    price: '$115',
    priceValue: 115,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'NEW COLOR',
    moreColors: '+8',
    swatches: ['#7998B8', '#4A4F57', '#D0D3D8'],
    sizes: ['8', '9', '10', '11'],
    colors: ['Blue', 'Grey'],
    productType: 'Everyday Sneakers',
    material: 'Canvas',
    categories: ["Men's Fashion"],
  },
  {
    name: "Men's Varsity Flex",
    variant: 'Parchment',
    price: '$125',
    priceValue: 125,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'PANTONE COLOR',
    moreColors: '+5',
    swatches: ['#D7D2C9', '#9E9B95', '#2E3136'],
    sizes: ['9', '10', '11', '12'],
    colors: ['White', 'Black'],
    productType: 'High Tops',
    material: 'Alternative-Leather',
    categories: ["Men's Fashion", "Men's Accessories"],
  },
  {
    name: "Men's Cloud Runner",
    variant: 'Bone White',
    price: '$132',
    priceValue: 132,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'NEW',
    moreColors: '+7',
    swatches: ['#E2DED5', '#9A958B', '#464A50'],
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['White', 'Grey'],
    productType: 'Running Shoes',
    material: 'Wool',
    categories: ["Men's Fashion"],
  },
  {
    name: "Men's Metro Sneaker",
    variant: 'Ink Navy',
    price: '$118',
    priceValue: 118,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'BESTSELLER',
    moreColors: '+4',
    swatches: ['#243248', '#6B7483', '#C6CBD3'],
    sizes: ['8', '9', '10', '11'],
    colors: ['Blue', 'Grey'],
    productType: 'Everyday Sneakers',
    material: 'Tree-Fiber-Blend',
    categories: ["Men's Fashion", 'Discount Deals'],
  },
  {
    name: "Men's Aero Street",
    variant: 'Cloud Grey',
    price: '$159',
    priceValue: 159,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'NEW',
    moreColors: '+3',
    swatches: ['#A8ADB5', '#494D55', '#F2F3F5'],
    sizes: ['9', '10', '11', '12'],
    colors: ['Grey', 'Black'],
    productType: 'Running Shoes',
    material: 'Sugar',
    categories: ["Men's Fashion", "Men's Accessories"],
  },
  {
    name: "Men's Trail Core",
    variant: 'Forest Ash',
    price: '$146',
    priceValue: 146,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'LIMITED',
    moreColors: '+2',
    swatches: ['#55624B', '#2D332B', '#D4D6D0'],
    sizes: ['9', '10', '11', '12', '13'],
    colors: ['Green', 'Black'],
    productType: 'Hiking Shoes',
    material: 'Tree',
    categories: ["Men's Fashion"],
  },
  {
    name: "Men's Court Lite",
    variant: 'Satin Black',
    price: '$121',
    priceValue: 121,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'NEW',
    moreColors: '+5',
    swatches: ['#22252B', '#727680', '#D9DCE2'],
    sizes: ['8', '9', '10', '11'],
    colors: ['Black', 'Grey'],
    productType: 'Everyday Sneakers',
    material: 'Canvas',
    categories: ["Men's Fashion", "Men's Accessories"],
  },
  {
    name: "Men's Comet Pro",
    variant: 'Stone Mix',
    price: '$138',
    priceValue: 138,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'TRENDING',
    moreColors: '+6',
    swatches: ['#BDB8AF', '#6A6861', '#34363B'],
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['Beige', 'Grey'],
    productType: 'Running Shoes',
    material: 'Wool',
    categories: ["Men's Fashion", 'Discount Deals'],
  },
  {
    name: "Women's Glide Loafer",
    variant: 'Light Sand',
    price: '$125',
    priceValue: 125,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'NEW COLOR',
    moreColors: '+5',
    swatches: ['#D7D1C1', '#C4B39A', '#7A7067'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Beige', 'White'],
    productType: 'Slip Ons',
    material: 'Canvas',
    categories: ["Women's Fashion", "Women's Accessories"],
  },
  {
    name: "Women's Cloud Runner",
    variant: 'Sea Glass',
    price: '$135',
    priceValue: 135,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'NEW',
    moreColors: '+6',
    swatches: ['#9EC0C8', '#D8D6CC', '#8F7D6A'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Blue', 'Beige'],
    productType: 'Running Shoes',
    material: 'Tree',
    categories: ["Women's Fashion"],
  },
  {
    name: "Women's Weekend Low",
    variant: 'Stone',
    price: '$115',
    priceValue: 115,
    image: 'assets/images/promotional_banner_1.webp',
    badge: 'PANTONE COLOR',
    moreColors: '+7',
    swatches: ['#BAB4A9', '#D5CEC2', '#8E8379'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Grey', 'White'],
    productType: 'Everyday Sneakers',
    material: 'Wool',
    categories: ["Women's Fashion", 'Discount Deals'],
  },
];
